### PR TITLE
Refactor: extract bencode tokenizer

### LINKED ISSUE #12: Find a better name for `BencodeParser` type
Yesterday, I discussed the main type name with @magecnion. It might not be a good name.

### Formal Definition of a Parser

> A parser is a component of a computer program that takes an input string (or byte stream) and produces a structured representation, often a tree-like format, based on a formal grammar. Parsers are typically used in the context of programming languages or data formats, where they validate and transform raw input into a more structured form for further processing.
 

Since the library converts bencoded data directly to JSON without creating an intermediary structured representation, the term "parser" might not entirely reflect its purpose. It implies more extensive processing than what the library does. 

### Alternative Names (ChatGPT)

1. **BencodeConverter**: Highlights the conversion process from bencode to JSON.
2. **BencodeToJson**: A clear and direct name describing the functionality.
3. **BencodeTransformer**: Suggests transforming the data from one format to another.
4. **BencodeSerializer**: Focuses on serializing bencoded data into JSON.
5. **BencodeStreamConverter**: Emphasizes that it works on streams and performs conversion.
6. **BencodeTranscoder**: Suggests translating data from one encoded format to another.
7. **BencodeJsonDumper**: Reflects the "dumping" nature of the process directly to JSON.
8. **BencodeInterpreter**: Suggests interpreting the bencoded data directly into JSON output.
9. **BencodeDecoder**: Focuses on decoding bencode and outputting JSON.
10. **BencodeEmitter**: Implies emitting JSON data directly from the bencode input.

cc @da2ce7 @magecnion

### PR DESCRIPTION
**Pull request by josecelano**
This refactoring changes the current implementation to extract the tokenizer. It splits parser logic into two types:

- **Tokenizer**: It returns bencoded tokens.
- **Generator**: It iterates over bencoded tokens to generate the JSON.

**NOTES**

- It keeps the custom recursivity (with explicit stack) for the time being, instead of using explicit recursivity like @da2ce7 did [here](https://github.com/torrust/bencode2json/issues/12#issuecomment-2508962547). I guess that could be changed later if we think it increases readability and maintainability.

**SUBTASKS**

- [x] Separate logic for tokenizer.
- [x] Extract tokenizer.
- [x] Remove `Writer` from the tokenizer. It's not needed.

**PERFORMANCE**

In the current version, bencoded strings are cached in memory before starting writing to the output (because we nned the whole string to check if it's a valid UTF-8). In this PR, bencoded integers are also cached in memory because the whole integer value is a token. This should not be a problem since integers are short, unlike strings.

**FUTURE PRs**

We could:

- [ ] Implement the `Iterator` trait for the tokenizer.
- [ ] Use recursion for the generator like @da2ce7's proposal [here](https://github.com/torrust/bencode2json/issues/12).
- [ ] Implement another generator for TOML, for example. Check if this design can be easily extended to other output formats.

### CODE REVIEW

**Comment by josecelano** [comment]
ACK ec6cc56d460975b4bbe8266255acf0cfdd82f6c7

**Comment by da2ce7** [comment]
@josecelano Looks good.

Just wondering, should we really tolerate line brakes in a Bencode Input?

**Comment by josecelano** [comment]
> @josecelano Looks good.
> 
> Just wondering, should we really tolerate line brakes in a Bencode Input?

Hi @da2ce7 I think I only added it to tolerate the line break at the end of the bencode value because it makes more flexible to run the application like this:

```console
echo "4:spam" | cargo run
```

If we don't tolerate line breaks you only can use this:

```console
printf "4:spam" | cargo run
```

I don't like it either. Maybe we can "clean" the input stream only in the main app.

**Comment by josecelano** [comment]
> @josecelano Looks good.
> 
> Just wondering, should we really tolerate line brakes in a Bencode Input?

I've opened an issue: https://github.com/torrust/bencode2json/issues/19

**Pull request merged**
